"""added_snapshot_and_max_submissions

Revision ID: 5d40c7fba088
Revises: 
Create Date: 2026-03-21 02:40:52.638051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d40c7fba088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('test_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('test_results', sa.Column('secure_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_test_results_secure_id'), 'test_results', ['secure_id'], unique=True)
    op.add_column('tests', sa.Column('max_submissions', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('secure_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tests_secure_id'), 'tests', ['secure_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_secure_id'), table_name='tests')
    op.drop_column('tests', 'secure_id')
    op.drop_column('tests', 'max_submissions')
    op.drop_index(op.f('ix_test_results_secure_id'), table_name='test_results')
    op.drop_column('test_results', 'secure_id')
    op.drop_column('test_results', 'test_snapshot')
    # ### end Alembic commands ###
